# Site settings
author: Andi Osika
title: For the Love of Data:
header-img: img/home-bg.png
email: andiosika@gmail.com
copyright_name: Andi Osika
description: > # this means to ignore newlines until "baseurl:"
  Data Everything Lover
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: andrea_osika
github_username:  andiosika

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
